name: Laravel

on:
  push:
    branches: [ '**' ]

jobs:

  laravel-tests:

    runs-on: ${{ matrix.os }}
    env:
      MYSQL_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: ''
      DB_PORT: 3306
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v3
      - uses: ankane/setup-mysql@v1
        with:
          mysql-version: 8.0
          database: laravel
      - run: mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql

      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.0'

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: php.ini setup for Windows
        if: matrix.os == 'windows-latest'
        run:
          (Get-Content C:\tools\php\php.ini) -Replace ';extension=pdo_mysql', 'extension=pdo_mysql' | Set-Content C:\tools\php\php.ini;
          (Get-Content C:\tools\php\php.ini) -Replace ';extension=fileinfo', 'extension=fileinfo' | Set-Content C:\tools\php\php.ini;
          (Get-Content C:\tools\php\php.ini) -Replace ';extension_dir = "ext"', 'extension_dir = "ext"' | Set-Content C:\tools\php\php.ini;
        shell: powershell
      - name: Install Dependencies
        run:
          composer require doctrine/dbal;
          composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Generate key
        run: php artisan key:generate
      - name: Clear Cache
        run: php artisan cache:clear; php artisan config:clear;
      - name: Migrate
        run: php artisan migrate:fresh
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit
